name: _ Run Tests
on:
  workflow_call:
    inputs:
      use-rpc-devnet:
        type: boolean
        default: false
      use-seq-devnet:
        type: boolean
        default: false
    secrets:
      TEST_PROVIDER_BASE_URL:
        required: false
      TEST_RPC_URL:
        required: false
      TEST_ACCOUNT_PRIVATE_KEY:
        required: false
      TEST_ACCOUNT_ADDRESS:
        required: false

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    # TODO - periodically check if conditional services are supported; https://github.com/actions/runner/issues/822
    services:
      devnet:
        # image: ${{ inputs.use-rpc-devnet && 'shardlabs/starknet-devnet:0.6.1-seed0' || inputs.use-seq-devnet && 'shardlabs/starknet-devnet:0.6.1-seed0' || '' }}
        image: ${{ (inputs.use-rpc-devnet || inputs.use-seq-devnet) && 'shardlabs/starknet-devnet:0.6.1-seed0' || '' }}
        # image: shardlabs/starknet-devnet:0.6.1-seed0
        ports:
          - 5050:5050

    # TODO - temporary conditional, remove if/when devnet RPC support is restored
    if: ${{ (!inputs.use-rpc-devnet) }}

    env:
      TEST_PROVIDER_BASE_URL: ${{ secrets.TEST_PROVIDER_BASE_URL }}
      TEST_RPC_URL: ${{ secrets.TEST_RPC_URL }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}

    steps:
      - run: echo ${{ secrets.TEST_PROVIDER_BASE_URL }}
      - run: echo ${{ secrets.TEST_RPC_URL }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm test
