name: Manual Release
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        type: boolean
        default: true
      dry-run:
        description: 'Dry run'
        type: boolean
        default: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci --ignore-scripts ${{ inputs.dry-run }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --debug ${{ inputs.debug }} --dry-run ${{ inputs.dry-run }}
