name: PR/Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  skip_check:
    name: Skip check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_duplicate.outputs.should_skip }}
    steps:
      - id: skip_duplicate
        uses: fkirc/skip-duplicate-actions@v5

  tests:
    name: Run test on ${{ matrix.name }}
    needs: [skip_check]
    if: needs.skip_check.outputs.should_skip != 'true'
    strategy:
      max-parallel: 1 # needed until we get a seperate account for the rpc provider, until then running them in parallel would result in a nonce issue
      matrix:
        name: [sequencer-goerli, rpc-goerli]
        include:
          - name: sequencer-goerli
            TEST_PROVIDER_BASE_URL: https://alpha4-2.starknet.io
          - name: rpc-goerli
            ENABLE_TEST_RPC_URL: true

    uses: ./.github/workflows/_test.yml
    secrets:
      TEST_PROVIDER_BASE_URL: ${{ matrix.TEST_PROVIDER_BASE_URL }}
      TEST_RPC_URL: ${{ matrix.ENABLE_TEST_RPC_URL && secrets.TEST_RPC_URL }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}

  release:
    name: Release
    needs: [skip_check, tests]
    if: |
      !cancelled() && !failure()
      && needs.skip_check.outputs.should_skip != ''
      && github.event_name == 'push'
    uses: ./.github/workflows/_release.yml
    secrets: inherit
